[build]
  publish = "dist/"
  command = "npm run generate"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false

[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    scriptSrc = "'self'"
    styleSrc = "'self'"
    fontSrc = "'self'"
    imgSrc = "'self'"
    manifestSrc = "'self'"
    baseUri = "'none'"
    formAction = "'none'"
    frameAncestors = "'none'"

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
  checkExternal = true
