[build]
  publish = "dist/"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'" # Required due to bug in Firefox when loading SVGs with <use> (https://bugzilla.mozilla.org/show_bug.cgi?id=1303364)
    childSrc = "'self'"
    mediaSrc = "'none'"
    objectSrc = "'none'"
    prefetchSrc = "'none'"
    scriptSrc = "'self'"
    styleSrc = "'self' 'unsafe-hashes'"
    fontSrc = "'self'"
    imgSrc = "'self'"
    manifestSrc = "'self'"
    connectSrc = "'self' https://firestore.googleapis.com"
    baseUri = "'none'"
    formAction = "'none'"
    frameAncestors = "'none'"

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
  checkExternal = true
  skipPatterns = ['https://out.valueourminds.com/the5/pledge/facebook', 'https://out.valueourminds.com/the5/pledge/twitter']
